<?php
@session_start();
require_once("../verificar.php");
require_once("../../conexao-radius-db.php");

$headends =['AMERICANA',
'ANAPOLIS',
'ARACAJU',
'ARACATUBA',
'ARAPONGAS',
'ARARAQUARA',
'BAGE',
'BAURU',
'BELEM',
'BELO HORIZONTE',
'BETIM',
'BLUMENAU',
'BOTUCATU',
'BRAGANCA PAULISTA',
'BRASILIA',
'CAMPINA GRANDE',
'CAMPINAS',
'CAMPO GRANDE',
'CAMPOS DOS GOYTACAZES',
'CAPAO DA CANOA',
'CARUARU',
'CASCAVEL',
'CAXIAS DO SUL',
'CHAPECO',
'CIANORTE',
'CRICIUMA',
'CUIABA',
'CURITIBA',
'FLORIANOPOLIS',
'FORTALEZA',
'FRANCA',
'GOIANIA',
'GOVERNADOR VALADARES',
'GUARAPUAVA',
'GUARATINGUETA',
'GUARUJA',
'GUARULHOS',
'IPATINGA',
'ITAPETININGA',
'JAU',
'JOAO PESSOA',
'JOINVILLE',
'JUIZ DE FORA',
'JUNDIAI',
'LIMEIRA',
'LONDRINA',
'MACAE',
'MACEIO',
'MANAUS',
'MARILIA',
'MARINGA',
'MOGI DAS CRUZES',
'MOGI MIRIM',
'NATAL',
'NOVO HAMBURGO',
'OSASCO',
'PALMAS',
'PASSO FUNDO',
'PELOTAS',
'PETROPOLIS',
'PIRACICABA',
'PONTA GROSSA',
'PORTO ALEGRE',
'PORTO VELHO',
'RECIFE',
'RIBEIRAO PRETO',
'RIO BRANCO',
'RIO DE JANEIRO',
'SALTO',
'SALVADOR',
'SANTA CRUZ DO SUL',
'SANTA MARIA',
'SANTO ANDRE',
'SANTOS',
'SAO CARLOS',
'SAO JOSE DO RIO PRETO',
'SAO JOSE DOS CAMPOS',
'SAO LUIS',
'SAO PAULO',
'SOROCABA',
'TAUBATE',
'TEOFILO OTONI',
'TERESINA',
'TERESOPOLIS',
'UBERABA',
'UBERLANDIA',
'URUGUAIANA',
'VITORIA',
'VOC',
'VOLTA REDONDA'];

$bruno = ['xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'LIMEIRA',
'xxxxxxxx'=>	'FORTALEZA',
'xxxxxxxx'=>	'PORTO VELHO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'NATAL',
'xxxxxxxx'=>	'BELEM',
'xxxxxxxx'=>	'GOVERNADOR VALADARES',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'ARACAJU',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO JOSE DOS CAMPOS',
'xxxxxxxx'=>	'ITAPETININGA',
'ATxxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'SOROCABA',
'xxxxxxxx'=>	'SALTO',
'xxxxxxxx'=>	'CARUARU',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'GUARULHOS',
'Nxxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'RIBEIRAO PRETO',
'xxxxxxxx'=>	'MACAE',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'FLORIANOPOLIS',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'BLUMENAU',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SALVADOR',
'xxxxxxxx'=>	'SAO LUIS',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'BELEM',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'TERESINA',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'GUARATINGUETA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BELEM',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'TERESOPOLIS',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'TAUBATE',
'xxxxxxxx'=>	'SAO JOSE DO RIO PRETO',
'xxxxxxxx'=>	'ARACATUBA',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'BRAGANCA PAULISTA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'ARAPONGAS',
'xxxxxxxx'=>	'RECIFE',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'CUIABA',
'xxxxxxxx'=>	'BAGE',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'SALTO',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'PIRACICABA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'BETIM',
'xxxxxxxx'=>	'CUIABA',
'xxxxxxxx'=>	'SAO LUIS',
'xxxxxxxx'=>	'PALMAS',
'xxxxxxxx'=>	'SALVADOR',
'xxxxxxxx'=>	'PETROPOLIS',
'xxxxxxxx'=>	'TAUBATE',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'PETROPOLIS',
'xxxxxxxx'=>	'PIRACICABA',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'ARACATUBA',
'xxxxxxxx'=>	'SANTA MARIA',
'xxxxxxxx'=>	'CAMPOS DOS GOYTACAZES',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'PASSO FUNDO',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'SANTO ANDRE',
'xxxxxxxx'=>	'PELOTAS',
'xxxxxxxx'=>	'SANTO ANDRE',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'BRASILIA',
'Nxxxxxxxx'=>	'FLORIANOPOLIS',
'xxxxxxxx'=>	'GUARAPUAVA',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'JOINVILLE',
'xxxxxxxx'=>	'UBERABA',
'xxxxxxxx'=>	'FORTALEZA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'BAURU',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'MACAE',
'xxxxxxxx'=>	'SALVADOR',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'SAO JOSE DOS CAMPOS',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'SAO JOSE DOS CAMPOS',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'CARUARU',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'CAMPOS DOS GOYTACAZES',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'AMERICANA',
'xxxxxxxx'=>	'TAUBATE',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'NATAL',
'xxxxxxxx'=>	'JUIZ DE FORA',
'xxxxxxxx'=>	'CAXIAS DO SUL',
'xxxxxxxx'=>	'BRAGANCA PAULISTA',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'TEOFILO OTONI',
'xxxxxxxx'=>	'PORTO VELHO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'RECIFE',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'CAMPO GRANDE',
'xxxxxxxx'=>	'PETROPOLIS',
'xxxxxxxx'=>	'RECIFE',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'JUIZ DE FORA',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'SOROCABA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'RECIFE',
'xxxxxxxx'=>	'RIBEIRAO PRETO',
'xxxxxxxx'=>	'PORTO VELHO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'PORTO ALEGRExxxxxxxx',
'xxxxxxxx'=>	'OSASCO',
'xxxxxxxx'=>	'VOLTA REDONDA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'RIO BRANCO',
'xxxxxxxx'=>	'OSASCO',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'MACEIO',
'xxxxxxxx'=>	'BAURU',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SALVADOR',
'xxxxxxxx'=>	'ANAPOLIS',
'xxxxxxxx'=>	'AMERICANA',
'xxxxxxxx'=>	'PASSO FUNDO',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'AMERICANA',
'xxxxxxxx'=>	'TERESINA',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'MACEIO',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'FLORIANOPOLIS',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'BOTUCATU',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'NATAL',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'RECIFE',
'xxxxxxxx'=>	'AMERICANA',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'CAMPINA GRANDE',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BELEM',
'xxxxxxxx'=>	'CAMPOS DOS GOYTACAZES',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'PELOTAS',
'xxxxxxxx'=>	'MANAUS',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'MARILIA',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'ANAPOLIS',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'JAU',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'CAMPOS DOS GOYTACAZES',
'xxxxxxxx'=>	'FLORIANOPOLIS',
'xxxxxxxx'=>	'ARACAJU',
'xxxxxxxx'=>	'BLUMENAU',
'xxxxxxxx'=>	'GUARATINGUETA',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'GUARUJA',
'Nxxxxxxxx'=>	'CAMPO GRANDE',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SAO CARLOS',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'SANTA CRUZ DO SUL',
'xxxxxxxx'=>	'SALVADOR',
'xxxxxxxx'=>	'RECIFE',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SANTOS',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'CAXIAS DO SUL',
'Nxxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'CRICIUMA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'CIANORTE',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'BELEM',
'xxxxxxxx'=>	'BETIM',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'ARACAJU',
'xxxxxxxx'=>	'VOLTA REDONDA',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'LONDRINA',
'xxxxxxxx'=>	'BLUMENAU',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'CAPAO DA CANOA',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'MOGI DAS CRUZES',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'FORTALEZA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'MOGI MIRIM',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BELEM',
'xxxxxxxx'=>	'MARINGA',
'xxxxxxxx'=>	'SANTO ANDRE',
'xxxxxxxx'=>	'SAO JOSE DO RIO PRETO',
'xxxxxxxx'=>	'BELO HORIZONTE',
'Nxxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'FLORIANOPOLIS',
'xxxxxxxx'=>	'LONDRINA',
'xxxxxxxx'=>	'LIMEIRA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'BLUMENAU',
'xxxxxxxx'=>	'VOLTA REDONDA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO JOSE DOS CAMPOS',
'xxxxxxxx'=>	'CAMPINA GRANDE',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'SAO CARLOS',
'xxxxxxxx'=>	'CASCAVEL',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'CUIABA',
'xxxxxxxx'=>	'IPATINGA',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'URUGUAIANA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BRASILIA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'TAUBATE',
'xxxxxxxx'=>	'BELEM',
'xxxxxxxx'=>	'AMERICANA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'JUNDIAI',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'PORTO ALEGRE',
'xxxxxxxx'=>	'CHAPECO',
'ROxxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'BRAGANCA PAULISTA',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'RIO BRANCO',
'xxxxxxxx'=>	'ARARAQUARA',
'xxxxxxxx'=>	'RIBEIRAO PRETO',
'xxxxxxxx'=>	'FRANCA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'NATAL',
'xxxxxxxx'=>	'SALVADOR',
'xxxxxxxx'=>	'VITORIA',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'JOINVILLE',
'xxxxxxxx'=>	'SAO LUIS',
'xxxxxxxx'=>	'SAO PAULO',
'xxxxxxxx'=>	'PALMAS',
'xxxxxxxx'=>	'GUARULHOS',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'MOGI DAS CRUZES',
'xxxxxxxx'=>	'NOVO HAMBURGO',
'Nxxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'TERESINA',
'xxxxxxxx'=>	'SALVADOR',
'xxxxxxxx'=>	'FLORIANOPOLIS',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'CAMPINAS',
'xxxxxxxx'=>	'JOAO PESSOA',
'xxxxxxxx'=>	'RIO DE JANEIRO',
'xxxxxxxx'=>	'UBERLANDIA',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'GOIANIA',
'xxxxxxxx'=>	'SAO CARLOS',
'xxxxxxxx'=>	'VOC',
'xxxxxxxx'=>	'MACEIO',
'xxxxxxxx'=>	'LIMEIRA',
'xxxxxxxx'=>	'AMERICANA',
'xxxxxxxx'=>	'BELO HORIZONTE',
'xxxxxxxx'=>	'SOROCABA',
'xxxxxxxx'=>	'FLORIANOPOLIS',
'xxxxxxxx'=>	'CAMPO GRANDE',
'xxxxxxxx'=>	'PONTA GROSSA',
'xxxxxxxx'=>	'CURITIBA',
'xxxxxxxx'=>	'VOC',
];

$contador = 0;
foreach($bruno as $chavebruno=> $valorbruno){
    print_r($chavebruno . "</br>") ;
    $query = $pdo->query("SELECT * FROM userinfo WHERE username='$chavebruno'");
    $res = $query->fetchAll(PDO::FETCH_ASSOC);
    $total_reg = @count($res);
    if($total_reg > 0){
        $contador++;
        $query = $pdo->query("UPDATE userinfo set city = '$valorbruno' where username = '$chavebruno';");
        $res = $query->fetchAll(PDO::FETCH_ASSOC);
        echo "Usuario cadastrado com sucesso - {$cityheadend}.";
    }
}
echo count($bruno);
echo $contador;
?>